/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CoursesJavaLanguage1RouteImport } from './routes/courses.java-language-1'
import { Route as CoursesCppLanguage2RouteImport } from './routes/courses.cpp-language-2'
import { Route as CoursesCLanguage1RouteImport } from './routes/courses.c-language-1'
import { Route as AdminStudentDataRouteImport } from './routes/admin.student-data'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminAiGeneratorRouteImport } from './routes/admin.ai-generator'
import { Route as AdminActivityLogsRouteImport } from './routes/admin.activity-logs'
import { Route as CoursesJavaLanguage1PracticeRouteImport } from './routes/courses.java-language-1.practice'
import { Route as CoursesCppLanguage2PracticeRouteImport } from './routes/courses.cpp-language-2.practice'
import { Route as CoursesCLanguage1PracticeRouteImport } from './routes/courses.c-language-1.practice'
import { Route as AttemptsAttemptIdResultRouteImport } from './routes/attempts.$attemptId.result'
import { Route as CoursesCLanguage1ExamsFinal2026FirstRouteImport } from './routes/courses.c-language-1.exams.final-2026-first'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesJavaLanguage1Route = CoursesJavaLanguage1RouteImport.update({
  id: '/courses/java-language-1',
  path: '/courses/java-language-1',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCppLanguage2Route = CoursesCppLanguage2RouteImport.update({
  id: '/courses/cpp-language-2',
  path: '/courses/cpp-language-2',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCLanguage1Route = CoursesCLanguage1RouteImport.update({
  id: '/courses/c-language-1',
  path: '/courses/c-language-1',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentDataRoute = AdminStudentDataRouteImport.update({
  id: '/admin/student-data',
  path: '/admin/student-data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiGeneratorRoute = AdminAiGeneratorRouteImport.update({
  id: '/admin/ai-generator',
  path: '/admin/ai-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/admin/activity-logs',
  path: '/admin/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesJavaLanguage1PracticeRoute =
  CoursesJavaLanguage1PracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => CoursesJavaLanguage1Route,
  } as any)
const CoursesCppLanguage2PracticeRoute =
  CoursesCppLanguage2PracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => CoursesCppLanguage2Route,
  } as any)
const CoursesCLanguage1PracticeRoute =
  CoursesCLanguage1PracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => CoursesCLanguage1Route,
  } as any)
const AttemptsAttemptIdResultRoute = AttemptsAttemptIdResultRouteImport.update({
  id: '/attempts/$attemptId/result',
  path: '/attempts/$attemptId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCLanguage1ExamsFinal2026FirstRoute =
  CoursesCLanguage1ExamsFinal2026FirstRouteImport.update({
    id: '/exams/final-2026-first',
    path: '/exams/final-2026-first',
    getParentRoute: () => CoursesCLanguage1Route,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/student-data': typeof AdminStudentDataRoute
  '/courses/c-language-1': typeof CoursesCLanguage1RouteWithChildren
  '/courses/cpp-language-2': typeof CoursesCppLanguage2RouteWithChildren
  '/courses/java-language-1': typeof CoursesJavaLanguage1RouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/courses/c-language-1/practice': typeof CoursesCLanguage1PracticeRoute
  '/courses/cpp-language-2/practice': typeof CoursesCppLanguage2PracticeRoute
  '/courses/java-language-1/practice': typeof CoursesJavaLanguage1PracticeRoute
  '/courses/c-language-1/exams/final-2026-first': typeof CoursesCLanguage1ExamsFinal2026FirstRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/student-data': typeof AdminStudentDataRoute
  '/courses/c-language-1': typeof CoursesCLanguage1RouteWithChildren
  '/courses/cpp-language-2': typeof CoursesCppLanguage2RouteWithChildren
  '/courses/java-language-1': typeof CoursesJavaLanguage1RouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/courses/c-language-1/practice': typeof CoursesCLanguage1PracticeRoute
  '/courses/cpp-language-2/practice': typeof CoursesCppLanguage2PracticeRoute
  '/courses/java-language-1/practice': typeof CoursesJavaLanguage1PracticeRoute
  '/courses/c-language-1/exams/final-2026-first': typeof CoursesCLanguage1ExamsFinal2026FirstRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/admin/activity-logs': typeof AdminActivityLogsRoute
  '/admin/ai-generator': typeof AdminAiGeneratorRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/student-data': typeof AdminStudentDataRoute
  '/courses/c-language-1': typeof CoursesCLanguage1RouteWithChildren
  '/courses/cpp-language-2': typeof CoursesCppLanguage2RouteWithChildren
  '/courses/java-language-1': typeof CoursesJavaLanguage1RouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/attempts/$attemptId/result': typeof AttemptsAttemptIdResultRoute
  '/courses/c-language-1/practice': typeof CoursesCLanguage1PracticeRoute
  '/courses/cpp-language-2/practice': typeof CoursesCppLanguage2PracticeRoute
  '/courses/java-language-1/practice': typeof CoursesJavaLanguage1PracticeRoute
  '/courses/c-language-1/exams/final-2026-first': typeof CoursesCLanguage1ExamsFinal2026FirstRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/activity-logs'
    | '/admin/ai-generator'
    | '/admin/feedback'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/student-data'
    | '/courses/c-language-1'
    | '/courses/cpp-language-2'
    | '/courses/java-language-1'
    | '/admin/'
    | '/attempts/$attemptId/result'
    | '/courses/c-language-1/practice'
    | '/courses/cpp-language-2/practice'
    | '/courses/java-language-1/practice'
    | '/courses/c-language-1/exams/final-2026-first'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/activity-logs'
    | '/admin/ai-generator'
    | '/admin/feedback'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/student-data'
    | '/courses/c-language-1'
    | '/courses/cpp-language-2'
    | '/courses/java-language-1'
    | '/admin'
    | '/attempts/$attemptId/result'
    | '/courses/c-language-1/practice'
    | '/courses/cpp-language-2/practice'
    | '/courses/java-language-1/practice'
    | '/courses/c-language-1/exams/final-2026-first'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/admin/activity-logs'
    | '/admin/ai-generator'
    | '/admin/feedback'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/student-data'
    | '/courses/c-language-1'
    | '/courses/cpp-language-2'
    | '/courses/java-language-1'
    | '/admin/'
    | '/attempts/$attemptId/result'
    | '/courses/c-language-1/practice'
    | '/courses/cpp-language-2/practice'
    | '/courses/java-language-1/practice'
    | '/courses/c-language-1/exams/final-2026-first'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminAiGeneratorRoute: typeof AdminAiGeneratorRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminStudentDataRoute: typeof AdminStudentDataRoute
  CoursesCLanguage1Route: typeof CoursesCLanguage1RouteWithChildren
  CoursesCppLanguage2Route: typeof CoursesCppLanguage2RouteWithChildren
  CoursesJavaLanguage1Route: typeof CoursesJavaLanguage1RouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AttemptsAttemptIdResultRoute: typeof AttemptsAttemptIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/java-language-1': {
      id: '/courses/java-language-1'
      path: '/courses/java-language-1'
      fullPath: '/courses/java-language-1'
      preLoaderRoute: typeof CoursesJavaLanguage1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/cpp-language-2': {
      id: '/courses/cpp-language-2'
      path: '/courses/cpp-language-2'
      fullPath: '/courses/cpp-language-2'
      preLoaderRoute: typeof CoursesCppLanguage2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/c-language-1': {
      id: '/courses/c-language-1'
      path: '/courses/c-language-1'
      fullPath: '/courses/c-language-1'
      preLoaderRoute: typeof CoursesCLanguage1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/student-data': {
      id: '/admin/student-data'
      path: '/admin/student-data'
      fullPath: '/admin/student-data'
      preLoaderRoute: typeof AdminStudentDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-generator': {
      id: '/admin/ai-generator'
      path: '/admin/ai-generator'
      fullPath: '/admin/ai-generator'
      preLoaderRoute: typeof AdminAiGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-logs': {
      id: '/admin/activity-logs'
      path: '/admin/activity-logs'
      fullPath: '/admin/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/java-language-1/practice': {
      id: '/courses/java-language-1/practice'
      path: '/practice'
      fullPath: '/courses/java-language-1/practice'
      preLoaderRoute: typeof CoursesJavaLanguage1PracticeRouteImport
      parentRoute: typeof CoursesJavaLanguage1Route
    }
    '/courses/cpp-language-2/practice': {
      id: '/courses/cpp-language-2/practice'
      path: '/practice'
      fullPath: '/courses/cpp-language-2/practice'
      preLoaderRoute: typeof CoursesCppLanguage2PracticeRouteImport
      parentRoute: typeof CoursesCppLanguage2Route
    }
    '/courses/c-language-1/practice': {
      id: '/courses/c-language-1/practice'
      path: '/practice'
      fullPath: '/courses/c-language-1/practice'
      preLoaderRoute: typeof CoursesCLanguage1PracticeRouteImport
      parentRoute: typeof CoursesCLanguage1Route
    }
    '/attempts/$attemptId/result': {
      id: '/attempts/$attemptId/result'
      path: '/attempts/$attemptId/result'
      fullPath: '/attempts/$attemptId/result'
      preLoaderRoute: typeof AttemptsAttemptIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/c-language-1/exams/final-2026-first': {
      id: '/courses/c-language-1/exams/final-2026-first'
      path: '/exams/final-2026-first'
      fullPath: '/courses/c-language-1/exams/final-2026-first'
      preLoaderRoute: typeof CoursesCLanguage1ExamsFinal2026FirstRouteImport
      parentRoute: typeof CoursesCLanguage1Route
    }
  }
}

interface CoursesCLanguage1RouteChildren {
  CoursesCLanguage1PracticeRoute: typeof CoursesCLanguage1PracticeRoute
  CoursesCLanguage1ExamsFinal2026FirstRoute: typeof CoursesCLanguage1ExamsFinal2026FirstRoute
}

const CoursesCLanguage1RouteChildren: CoursesCLanguage1RouteChildren = {
  CoursesCLanguage1PracticeRoute: CoursesCLanguage1PracticeRoute,
  CoursesCLanguage1ExamsFinal2026FirstRoute:
    CoursesCLanguage1ExamsFinal2026FirstRoute,
}

const CoursesCLanguage1RouteWithChildren =
  CoursesCLanguage1Route._addFileChildren(CoursesCLanguage1RouteChildren)

interface CoursesCppLanguage2RouteChildren {
  CoursesCppLanguage2PracticeRoute: typeof CoursesCppLanguage2PracticeRoute
}

const CoursesCppLanguage2RouteChildren: CoursesCppLanguage2RouteChildren = {
  CoursesCppLanguage2PracticeRoute: CoursesCppLanguage2PracticeRoute,
}

const CoursesCppLanguage2RouteWithChildren =
  CoursesCppLanguage2Route._addFileChildren(CoursesCppLanguage2RouteChildren)

interface CoursesJavaLanguage1RouteChildren {
  CoursesJavaLanguage1PracticeRoute: typeof CoursesJavaLanguage1PracticeRoute
}

const CoursesJavaLanguage1RouteChildren: CoursesJavaLanguage1RouteChildren = {
  CoursesJavaLanguage1PracticeRoute: CoursesJavaLanguage1PracticeRoute,
}

const CoursesJavaLanguage1RouteWithChildren =
  CoursesJavaLanguage1Route._addFileChildren(CoursesJavaLanguage1RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminAiGeneratorRoute: AdminAiGeneratorRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminStudentDataRoute: AdminStudentDataRoute,
  CoursesCLanguage1Route: CoursesCLanguage1RouteWithChildren,
  CoursesCppLanguage2Route: CoursesCppLanguage2RouteWithChildren,
  CoursesJavaLanguage1Route: CoursesJavaLanguage1RouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AttemptsAttemptIdResultRoute: AttemptsAttemptIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
